$(document).ready(function(){
  $("#homepage").show();
  $("#mcn-twitter").show();
  $("#homepage-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/VaaFaG6.jpg");
    $(".page").hide();
    $("#homepage").show();
    $(".twitter").hide();
    $("#mcn-twitter").show();
  });
  $("#mcn-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/hqt7FMp.jpg");
    $(".page").hide();
    $("#mcn-page").show();
    $(".twitter").hide();
    $("#mcn-twitter").show();
  });
  $("#adlington-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/6Q5tfd4.jpg");
    $(".page").hide();
    $("#adlington-page").show();
    $(".twitter").hide();
    $("#adlington-twitter").show();
  });
  $("#anders-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/Kkx3AF6.jpg");
    $(".page").hide();
    $("#anders-page").show();
    $(".twitter").hide();
    $("#anders-twitter").show();
  });
  $("#arkas-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/TkBZ9cn.jpg");
    $(".page").hide();
    $("#arkas-page").show();
    $(".twitter").hide();
    $("#arkas-twitter").show();
  });
  $("#aurey-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/LkuH3um.jpg");
    $(".page").hide();
    $("#aurey-page").show();
    $(".twitter").hide();
    $("#aurey-twitter").show();
  });
  $("#avidya-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/3IYVELz.png");
    $(".page").hide();
    $("#avidya-page").show();
    $(".twitter").hide();
    $("#avidya-twitter").show();
  });
  $("#coe-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/3dOfD12.jpg");
    $(".page").hide();
    $("#coe-page").show();
    $(".twitter").hide();
    $("#coe-twitter").show();
  });
  $("#dire-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/Cyy4exo.jpg");
    $(".page").hide();
    $("#dire-page").show();
    $(".twitter").hide();
    $("#dire-twitter").show();
  });
  $("#doc-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/GIjyZuQ.jpg");
    $(".page").hide();
    $("#doc-page").show();
    $(".twitter").hide();
    $("#doc-twitter").show();
  });
  $("#guude-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/jSx1hVP.jpg");
    $(".page").hide();
    $("#guude-page").show();
    $(".twitter").hide();
    $("#guude-twitter").show();
  });
  $("#jsano-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/i2H3Kas.jpg");
    $(".page").hide();
    $("#jsano-page").show();
    $(".twitter").hide();
    $("#jsano-twitter").show();
  });
  $("#kurt-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/s4pbX91.jpg");
    $(".page").hide();
    $("#kurt-page").show();
    $(".twitter").hide();
    $("#kurt-twitter").show();
  });
  $("#mhykol-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/c9oi7HV.jpg");
    $(".page").hide();
    $("#mhykol-page").show();
    $(".twitter").hide();
    $("#mhykol-twitter").show();
  });
  $("#millbee-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/TtogD4B.jpg");
    $(".page").hide();
    $("#millbee-page").show();
    $(".twitter").hide();
    $("#millbee-twitter").show();
  });
  $("#nebris-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/xGTwW3q.jpg");
    $(".page").hide();
    $("#nebris-page").show();
    $(".twitter").hide();
    $("#nebris-twitter").show();
  });
  $("#chad-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/gIH1S85.jpg");
    $(".page").hide();
    $("#chad-page").show();
    $(".twitter").hide();
    $("#chad-twitter").show();
  });
  $("#pak-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/TeWrrwb.jpg");
    $(".page").hide();
    $("#pak-page").show();
    $(".twitter").hide();
    $("#pak-twitter").show();
  });
  $("#pause-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/dTGP9eJ.jpg");
    $(".page").hide();
    $("#pause-page").show();
    $(".twitter").hide();
    $("#pause-twitter").show();
  });
  $("#pyro-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/GDuWTgN.jpg");
    $(".page").hide();
    $("#pyro-page").show();
    $(".twitter").hide();
    $("#pyro-twitter").show();
  });
  $("#seth-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/sZ50TK4.jpg");
    $(".page").hide();
    $("#seth-page").show();
    $(".twitter").hide();
    $("#seth-twitter").show();
  });
  $("#sev-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/pREqEMJ.jpg");
    $(".page").hide();
    $("#sev-page").show();
    $(".twitter").hide();
    $("#sev-twitter").show();
  });
  $("#mc-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/hr7qKo7.jpg");
    $(".page").hide();
    $("#mc-page").show();
    $(".twitter").hide();
    $("#mc-twitter").show();
  });
  $("#vechs-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/Pe22eqU.jpg");
    $(".page").hide();
    $("#vechs-page").show();
    $(".twitter").hide();
    $("#vechs-twitter").show();
  });
  $("#beef-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/CEzpqdw.jpg");
    $(".page").hide();
    $("#beef-page").show();
    $(".twitter").hide();
    $("#beef-twitter").show();
  });
  $("#baj-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/RZPh04i.jpg");
    $(".page").hide();
    $("#baj-page").show();
    $(".twitter").hide();
    $("#baj-twitter").show();
  });
  $("#zisteau-icon").click(function(){
    $("#banner").attr("src","http://i.imgur.com/7BcI8wA.jpg");
    $(".page").hide();
    $("#zisteau-page").show();
    $(".twitter").hide();
    $("#zisteau-twitter").show();
  });
});
